# Generated by Django 4.1.3 on 2022-11-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangatitle',
            name='authors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mangatitle',
            name='chapterCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mangatitle',
            name='endDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mangatitle',
            name='firstCoverImage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mangatitle',
            name='genres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mangatitle',
            name='startDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mangatitle',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mangatitle',
            name='volumeCount',
            field=models.IntegerField(default=0),
        ),
    ]
