# Generated by Django 4.1.3 on 2022-11-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_mangatitle_enddate_alter_mangatitle_startdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangatitle',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='mangatitle',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='mangatitle',
            name='startDate',
        ),
        migrations.AlterField(
            model_name='mangatitle',
            name='chapterCount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mangatitle',
            name='volumeCount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
