# Generated by Django 4.1.3 on 2022-11-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_mangatitle_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangatitle',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='mangatitle',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
