# Generated by Django 4.1.3 on 2022-11-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_mangatitle_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='mangatitle',
            name='authors',
        ),
        migrations.AddField(
            model_name='mangatitle',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, related_name='authors', to='base.mangaauthor'),
        ),
    ]
