# Generated by Django 4.1.3 on 2022-11-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_mangaauthor_remove_mangatitle_authors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='mangatitle',
            name='genres',
        ),
        migrations.AddField(
            model_name='mangatitle',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='genres', to='base.genre'),
        ),
    ]
