# Generated by Django 4.1.3 on 2022-11-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_genre_remove_mangatitle_genres_mangatitle_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangatitle',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authors', to='base.mangaauthor'),
        ),
        migrations.AlterField(
            model_name='mangatitle',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mangatitle',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='genres', to='base.genre'),
        ),
    ]
