# Generated by Django 4.1.3 on 2022-11-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_mangatitle_authors_alter_mangatitle_enddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mangatitle',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='mangaauthor',
            name='name',
        ),
        migrations.AddField(
            model_name='mangaauthor',
            name='firstName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mangaauthor',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
