# Generated by Django 4.1.3 on 2022-11-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_name_mangatitle_title_remove_mangaauthor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangaauthor',
            name='firstName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mangaauthor',
            name='surname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
